name: Infrastructure
on: push

# https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#jobsjob_idcontainer

env:
  TEST_TAG: moonwalkers/terraform:runnow

jobs:
  dev:
    runs-on: ubuntu-latest
    environment:
      name: dev
    steps:
    
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and export to Docker
        uses: docker/build-push-action@v2
        with:
          load: true
          tags: ${{ env.TEST_TAG }}
          secrets: |
            "TERRAFORM_TOKEN=${{ secrets.TERRAFORM_TOKEN }}"
            "GCP_CREDENTIAL=${{ secrets.GCP_CREDENTIAL }}"
            "BUCKET=${{ secrets.BUCKET_DEV }}"
            "TFVARS=${{ secrets.TFVARS_DEV }}"
            
      -
        name: Run the image
        run: |
          docker run --rm ${{ env.TEST_TAG }}
        
  prod:
    runs-on: ubuntu-latest
    #needs approval
    environment:
      name: prod
    steps:
      
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and export to Docker
        uses: docker/build-push-action@v2
        with:
          load: true
          tags: ${{ env.TEST_TAG }}
          secrets: |
            "TERRAFORM_TOKEN=${{ secrets.TERRAFORM_TOKEN }}"
            "GCP_CREDENTIAL=${{ secrets.GCP_CREDENTIAL_PROD }}"
            "BUCKET=${{ secrets.BUCKET_PROD }}"
            "TFVARS=${{ secrets.TFVARS_PROD }}"
            
      - name: Run the image
        run: |
          docker run --rm ${{ env.TEST_TAG }}        
